#!/usr/bin/env bash
set -euo pipefail

# ═══════════════════════════════════════════════
# Shadow API Validation Platform — Setup Wizard
# ═══════════════════════════════════════════════

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

banner() {
    echo ""
    echo -e "${PURPLE}${BOLD}"
    echo "  ╔══════════════════════════════════════════════════════╗"
    echo "  ║   Shadow API Validation Platform — Setup Wizard     ║"
    echo "  ╚══════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo -e "  ${DIM}One-command setup for the entire platform${NC}"
    echo ""
}

check_command() {
    if command -v "$1" &> /dev/null; then
        echo -e "  ${GREEN}[OK]${NC} $2"
        return 0
    else
        echo -e "  ${RED}[MISSING]${NC} $2"
        return 1
    fi
}

check_version() {
    local cmd="$1"
    local name="$2"
    local min_major="$3"
    local version_flag="${4:---version}"

    if ! command -v "$cmd" &> /dev/null; then
        echo -e "  ${RED}[MISSING]${NC} $name"
        return 1
    fi

    local version
    version=$($cmd $version_flag 2>&1 | head -1 | grep -oP '\d+\.\d+' | head -1)
    local major
    major=$(echo "$version" | cut -d. -f1)

    if [ "$major" -ge "$min_major" ] 2>/dev/null; then
        echo -e "  ${GREEN}[OK]${NC} $name (v$version)"
        return 0
    else
        echo -e "  ${YELLOW}[OUTDATED]${NC} $name (v$version, need v$min_major+)"
        return 1
    fi
}

banner

# ── Step 1: Check Prerequisites ──
echo -e "${CYAN}${BOLD}  Step 1: Checking Prerequisites${NC}"
echo -e "  ${DIM}─────────────────────────────────${NC}"

CRITICAL_MISSING=0

check_version "docker" "Docker" 20 || CRITICAL_MISSING=1
check_command "docker-compose" "Docker Compose" || {
    # Try docker compose (v2)
    if docker compose version &> /dev/null; then
        echo -e "  ${GREEN}[OK]${NC} Docker Compose (v2 plugin)"
    else
        CRITICAL_MISSING=1
    fi
}
check_version "node" "Node.js" 18 || CRITICAL_MISSING=1

# Optional
check_version "java" "Java" 17 "-version" || echo -e "  ${DIM}       (optional — needed for local Java dev only)${NC}"
check_version "python3" "Python" 3 || echo -e "  ${DIM}       (optional — needed for CLI tools and AI service dev)${NC}"

echo ""

if [ "$CRITICAL_MISSING" -eq 1 ]; then
    echo -e "  ${RED}${BOLD}Critical prerequisites missing!${NC}"
    echo -e "  ${DIM}Install Docker: https://docs.docker.com/get-docker/${NC}"
    echo -e "  ${DIM}Install Node.js: https://nodejs.org/${NC}"
    echo ""
    read -p "  Continue anyway? [y/N]: " CONTINUE
    if [[ ! "$CONTINUE" =~ ^[Yy]$ ]]; then
        echo -e "  ${DIM}Setup cancelled.${NC}"
        exit 1
    fi
fi

# ── Step 2: Interactive Configuration ──
echo -e "${CYAN}${BOLD}  Step 2: Platform Configuration${NC}"
echo -e "  ${DIM}─────────────────────────────────${NC}"

read -p "  Enter your Supabase Project URL [https://your-project.supabase.co]: " SUPABASE_URL
SUPABASE_URL=${SUPABASE_URL:-https://your-project.supabase.co}

read -s -p "  Enter your Supabase Anon Key: " SUPABASE_ANON_KEY
echo ""
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-your-supabase-anon-key}

read -s -p "  Enter your Gemini API Key (optional, press Enter to skip): " GEMINI_API_KEY
echo ""
GEMINI_API_KEY=${GEMINI_API_KEY:-}

read -s -p "  Enter your Supabase DB Password (for backend services): " SUPABASE_DB_PASSWORD
echo ""
SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD:-}

echo ""

# ── Step 3: Generate Configuration Files ──
echo -e "${CYAN}${BOLD}  Step 3: Generating Configuration${NC}"
echo -e "  ${DIM}─────────────────────────────────${NC}"

# Generate .env
cat > "$SCRIPT_DIR/.env" << EOF
# Shadow Deploy Platform Configuration
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Supabase
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}

# AI Service
GEMINI_API_KEY=${GEMINI_API_KEY}

# Service Ports (change if conflicts)
DASHBOARD_PORT=3000
NGINX_PROXY_PORT=8080
API_SERVICE_PORT=8083
AI_SERVICE_PORT=8000
INGESTION_PORT=8081
COMPARISON_PORT=8082
GRAFANA_PORT=3001
PROMETHEUS_PORT=9090
EOF
echo -e "  ${GREEN}[OK]${NC} Generated .env"

# Generate dashboard/.env.local
cat > "$SCRIPT_DIR/dashboard/.env.local" << EOF
VITE_SUPABASE_URL=${SUPABASE_URL}
VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
EOF
echo -e "  ${GREEN}[OK]${NC} Generated dashboard/.env.local"

# Generate supabase.ts
cat > "$SCRIPT_DIR/dashboard/src/services/supabase.ts" << EOF
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '${SUPABASE_URL}';
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || '${SUPABASE_ANON_KEY}';

if (SUPABASE_URL === 'https://your-project.supabase.co') {
    console.warn('Supabase URL not configured. Run \`./setup.sh\` or set VITE_SUPABASE_URL in dashboard/.env.local');
}

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
EOF
echo -e "  ${GREEN}[OK]${NC} Generated dashboard/src/services/supabase.ts"

echo ""

# ── Step 4: Database Migration ──
read -p "  Run Supabase schema migration now? (Requires Supabase SQL Editor) [y/N]: " RUN_MIGRATE
if [[ "$RUN_MIGRATE" =~ ^[Yy]$ ]]; then
    echo ""
    echo -e "  ${YELLOW}${BOLD}Manual Step Required:${NC}"
    echo -e "  ${DIM}1. Go to your Supabase Dashboard -> SQL Editor -> New Query${NC}"
    echo -e "  ${DIM}2. Paste the contents of: dashboard/supabase-schema.sql${NC}"
    echo -e "  ${DIM}3. Click 'Run'${NC}"
    echo ""
    read -p "  Press Enter when done..."
fi

# ── Step 5: Start Services ──
echo ""
read -p "  Start all services now? [Y/n]: " START_SERVICES
START_SERVICES=${START_SERVICES:-Y}

if [[ "$START_SERVICES" =~ ^[Yy]$ ]]; then
    echo ""
    echo -e "  ${CYAN}Starting all services...${NC}"
    cd "$SCRIPT_DIR"
    docker-compose up -d --build

    echo ""
    echo -e "  ${CYAN}Waiting for services to become healthy...${NC}"
    python3 cli/healthcheck.py --wait --timeout 120 || true
fi

# ── Summary ──
echo ""
echo -e "${GREEN}${BOLD}  Setup Complete!${NC}"
echo -e "  ${DIM}═════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BOLD}Service URLs:${NC}"
echo -e "  ${DIM}Dashboard:${NC}          ${CYAN}http://localhost:3000${NC}"
echo -e "  ${DIM}NGINX Proxy:${NC}        ${CYAN}http://localhost:8080${NC}"
echo -e "  ${DIM}API Service:${NC}        ${CYAN}http://localhost:8083${NC}"
echo -e "  ${DIM}AI Service:${NC}         ${CYAN}http://localhost:8005${NC}"
echo -e "  ${DIM}Ingestion Service:${NC}  ${CYAN}http://localhost:8081${NC}"
echo -e "  ${DIM}Grafana:${NC}            ${CYAN}http://localhost:3001${NC}  ${DIM}(admin/shadow-admin)${NC}"
echo -e "  ${DIM}Prometheus:${NC}         ${CYAN}http://localhost:9090${NC}"
echo ""
echo -e "  ${BOLD}Quick Commands:${NC}"
echo -e "  ${DIM}make health${NC}     — Check all service health"
echo -e "  ${DIM}make logs${NC}       — Tail all service logs"
echo -e "  ${DIM}make dev${NC}        — Start dashboard in dev mode"
echo -e "  ${DIM}make stop${NC}       — Stop all services"
echo ""
