# ═══════════════════════════════════════════════
# Shadow API Validation Platform — Setup Wizard
# PowerShell Edition
# ═══════════════════════════════════════════════

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

function Write-Color {
    param([string]$Text, [ConsoleColor]$Color = "White")
    Write-Host $Text -ForegroundColor $Color
}

function Show-Banner {
    Write-Host ""
    Write-Color "  ╔══════════════════════════════════════════════════════╗" Magenta
    Write-Color "  ║   Shadow API Validation Platform — Setup Wizard     ║" Magenta
    Write-Color "  ╚══════════════════════════════════════════════════════╝" Magenta
    Write-Host ""
    Write-Color "  One-command setup for the entire platform" DarkGray
    Write-Host ""
}

function Test-Command {
    param([string]$Command, [string]$Name)
    if (Get-Command $Command -ErrorAction SilentlyContinue) {
        Write-Host "  [OK] $Name" -ForegroundColor Green
        return $true
    } else {
        Write-Host "  [MISSING] $Name" -ForegroundColor Red
        return $false
    }
}

function Test-CommandVersion {
    param(
        [string]$Command,
        [string]$Name,
        [int]$MinMajor,
        [string]$VersionFlag = "--version"
    )
    if (-not (Get-Command $Command -ErrorAction SilentlyContinue)) {
        Write-Host "  [MISSING] $Name" -ForegroundColor Red
        return $false
    }
    try {
        $versionOutput = & $Command $VersionFlag 2>&1 | Select-Object -First 1
        $versionStr = [string]$versionOutput
        if ($versionStr -match '(+
)') {
            $ver = $matches[1]
            $major = [int]($ver.Split('.')[0])
            if ($major -ge $MinMajor) {
                Write-Host "  [OK] $Name (v$ver)" -ForegroundColor Green
                return $true
            } else {
                $msg = "  [OUTDATED] " + $Name + " (v" + $ver + ", need v" + $MinMajor + "+)"
                Write-Host $msg -ForegroundColor Yellow
                return $false
            }
        } else {
            Write-Host "  [OK] $Name" -ForegroundColor Green
            return $true
        }
    } catch {
        Write-Host "  [MISSING] $Name" -ForegroundColor Red
        return $false
    }
}

Show-Banner

# ── Step 1: Check Prerequisites ──
Write-Color "  Step 1: Checking Prerequisites" Cyan
Write-Color "  ---------------------------------" DarkGray

$CriticalMissing = $false

if (-not (Test-CommandVersion "docker" "Docker" 20)) { $CriticalMissing = $true }
if (-not (Test-Command "docker-compose" "Docker Compose")) {
    try {
        docker compose version 2>$null | Out-Null
        Write-Host "  [OK] Docker Compose (v2 plugin)" -ForegroundColor Green
    } catch {
        $CriticalMissing = $true
    }
}
if (-not (Test-CommandVersion "node" "Node.js" 18)) { $CriticalMissing = $true }

# Optional
Test-CommandVersion "java" "Java (optional)" 17 "-version" | Out-Null
Test-CommandVersion "python" "Python (optional)" 3 | Out-Null

Write-Host ""

if ($CriticalMissing) {
    Write-Color "  Critical prerequisites missing!" Red
    Write-Color "  Install Docker: https://docs.docker.com/get-docker/" DarkGray
    Write-Color "  Install Node.js: https://nodejs.org/" DarkGray
    Write-Host ""
    $Continue = Read-Host "  Continue anyway? [y/N]"
    if ($Continue -ne "y" -and $Continue -ne "Y") {
        Write-Color "  Setup cancelled." DarkGray
        exit 1
    }
}

# ── Step 2: Interactive Configuration ──
Write-Color "  Step 2: Platform Configuration" Cyan
Write-Color "  ---------------------------------" DarkGray

$SupabaseUrl = Read-Host "  Enter your Supabase Project URL [https://your-project.supabase.co]"
if ([string]::IsNullOrWhiteSpace($SupabaseUrl)) { $SupabaseUrl = "https://your-project.supabase.co" }

$SupabaseAnonKey = Read-Host "  Enter your Supabase Anon Key" -AsSecureString
$SupabaseAnonKeyPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($SupabaseAnonKey))
if ([string]::IsNullOrWhiteSpace($SupabaseAnonKeyPlain)) { $SupabaseAnonKeyPlain = "your-supabase-anon-key" }

$GeminiApiKey = Read-Host "  Enter your Gemini API Key - optional, press Enter to skip" -AsSecureString
$GeminiApiKeyPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($GeminiApiKey))

$SupabaseDbPassword = Read-Host "  Enter your Supabase DB Password" -AsSecureString
$SupabaseDbPasswordPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($SupabaseDbPassword))

Write-Host ""

# ── Step 3: Generate Configuration Files ──
Write-Color "  Step 3: Generating Configuration" Cyan
Write-Color "  ---------------------------------" DarkGray

$Timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ"
$nl = [Environment]::NewLine

# Generate .env
$envContent = '# Shadow Deploy Platform Configuration' + $nl
$envContent += '# Generated by setup.ps1 on ' + $Timestamp + $nl
$envContent += $nl
$envContent += '# Supabase' + $nl
$envContent += 'SUPABASE_URL=' + $SupabaseUrl + $nl
$envContent += 'SUPABASE_ANON_KEY=' + $SupabaseAnonKeyPlain + $nl
$envContent += 'SUPABASE_DB_PASSWORD=' + $SupabaseDbPasswordPlain + $nl
$envContent += $nl
$envContent += '# AI Service' + $nl
$envContent += 'GEMINI_API_KEY=' + $GeminiApiKeyPlain + $nl
$envContent += $nl
$envContent += '# Service Ports - change if conflicts' + $nl
$envContent += 'DASHBOARD_PORT=3000' + $nl
$envContent += 'NGINX_PROXY_PORT=8080' + $nl
$envContent += 'API_SERVICE_PORT=8083' + $nl
$envContent += 'AI_SERVICE_PORT=8000' + $nl
$envContent += 'INGESTION_PORT=8081' + $nl
$envContent += 'COMPARISON_PORT=8082' + $nl
$envContent += 'GRAFANA_PORT=3001' + $nl
$envContent += 'PROMETHEUS_PORT=9090'
$envPath = Join-Path $ScriptDir '.env'
[System.IO.File]::WriteAllText($envPath, $envContent)
Write-Host "  [OK] Generated .env" -ForegroundColor Green

# Generate dashboard/.env.local
$dashEnvContent = 'VITE_SUPABASE_URL=' + $SupabaseUrl + $nl
$dashEnvContent += 'VITE_SUPABASE_ANON_KEY=' + $SupabaseAnonKeyPlain
$dashEnvPath = Join-Path $ScriptDir 'dashboard'
$dashEnvPath = Join-Path $dashEnvPath '.env.local'
[System.IO.File]::WriteAllText($dashEnvPath, $dashEnvContent)
Write-Host "  [OK] Generated dashboard/.env.local" -ForegroundColor Green

# Generate supabase.ts using string concatenation with single-quoted strings
# This avoids all PS 5.1 parse issues with JS keywords like const/export/if
$pipe = [string]([char]124) + [string]([char]124)
$comma = [string]([char]44)

$tsContent = ''
$tsContent += 'import { createClient } from ' + [char]39 + '@supabase/supabase-js' + [char]39 + ';' + $nl
$tsContent += $nl
$tsContent += 'const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ' + $pipe + ' ' + [char]39 + $SupabaseUrl + [char]39 + ';' + $nl
$tsContent += 'const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ' + $pipe + ' ' + [char]39 + $SupabaseAnonKeyPlain + [char]39 + ';' + $nl
$tsContent += $nl
$tsContent += 'if (SUPABASE_URL === ' + [char]39 + 'https://your-project.supabase.co' + [char]39 + ') {' + $nl
$tsContent += '    console.warn(' + [char]39 + 'Supabase URL not configured. Run ./setup.sh or set VITE_SUPABASE_URL in dashboard/.env.local' + [char]39 + ');' + $nl
$tsContent += '}' + $nl
$tsContent += $nl
$tsContent += 'export const supabase = createClient(SUPABASE_URL' + $comma + ' SUPABASE_ANON_KEY);' + $nl

$tsDir = Join-Path $ScriptDir 'dashboard'
$tsDir = Join-Path $tsDir 'src'
$tsDir = Join-Path $tsDir 'services'
$tsPath = Join-Path $tsDir 'supabase.ts'
[System.IO.File]::WriteAllText($tsPath, $tsContent)
Write-Host "  [OK] Generated dashboard/src/services/supabase.ts" -ForegroundColor Green

Write-Host ""

# ── Step 4: Database Migration ──
$RunMigrate = Read-Host "  Run Supabase schema migration now? [y/N]"
if ($RunMigrate -eq "y" -or $RunMigrate -eq "Y") {
    Write-Host ""
    Write-Color "  Manual Step Required:" Yellow
    Write-Color "  1. Go to your Supabase Dashboard -> SQL Editor -> New Query" DarkGray
    Write-Color "  2. Paste the contents of: dashboard/supabase-schema.sql" DarkGray
    Write-Color "  3. Click Run" DarkGray
    Write-Host ""
    Read-Host "  Press Enter when done"
}

# ── Step 5: Start Services ──
Write-Host ""
$StartServices = Read-Host "  Start all services now? [Y/n]"
if ([string]::IsNullOrWhiteSpace($StartServices)) { $StartServices = "Y" }

if ($StartServices -eq "y" -or $StartServices -eq "Y") {
    Write-Host ""
    Write-Color "  Starting all services..." Cyan
    Set-Location $ScriptDir
    docker-compose up -d --build

    Write-Host ""
    Write-Color "  Waiting for services to become healthy..." Cyan
    python cli/healthcheck.py --wait --timeout 120
}

# ── Summary ──
Write-Host ""
Write-Color "  Setup Complete!" Green
Write-Color "  =========================================" DarkGray
Write-Host ""
Write-Color "  Service URLs:" White
Write-Host "  Dashboard:          " -NoNewLine; Write-Color "http://localhost:3000" Cyan
Write-Host "  NGINX Proxy:        " -NoNewLine; Write-Color "http://localhost:8080" Cyan
Write-Host "  API Service:        " -NoNewLine; Write-Color "http://localhost:8083" Cyan
Write-Host "  AI Service:         " -NoNewLine; Write-Color "http://localhost:8005" Cyan
Write-Host "  Ingestion Service:  " -NoNewLine; Write-Color "http://localhost:8081" Cyan
Write-Host "  Grafana:            " -NoNewLine; Write-Color "http://localhost:3001" Cyan
Write-Host "  Prometheus:         " -NoNewLine; Write-Color "http://localhost:9090" Cyan
Write-Host ""
Write-Color "  Quick Commands:" White
Write-Color "  make health     - Check all service health" DarkGray
Write-Color "  make logs       - Tail all service logs" DarkGray
Write-Color "  make dev        - Start dashboard in dev mode" DarkGray
Write-Color "  make stop       - Stop all services" DarkGray
Write-Host ""