#!/usr/bin/env python3
"""
shadowctl — Shadow API Validation Platform CLI

Commands:
    shadowctl init              Interactive setup wizard
    shadowctl health            Check all service health
    shadowctl configure         Natural language NGINX configuration
    shadowctl test              Quick website comparison test
    shadowctl status            Show platform status
    shadowctl report            Generate validation report
    shadowctl deployment-status Check deployment status
"""

import argparse
import json
import sys
import os
import time
import socket
import urllib.request
import urllib.error
from datetime import datetime
from getpass import getpass

AI_URL = os.getenv("SHADOW_AI_URL", "http://localhost:8005/api/v1")

# ── Colors ──
class Colors:
    RED = "\033[91m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    BLUE = "\033[94m"
    PURPLE = "\033[95m"
    CYAN = "\033[96m"
    BOLD = "\033[1m"
    DIM = "\033[2m"
    RESET = "\033[0m"

def c(text, color):
    return f"{color}{text}{Colors.RESET}"

def banner():
    print(c("""
 ══════════════════════════════════════════════════
   Shadow API Validation Platform — Setup Wizard
 ══════════════════════════════════════════════════
""", Colors.CYAN))


# ── Init Command ──
def cmd_init(args):
    banner()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.dirname(script_dir)

    print(c("  Step 1: API Configuration", Colors.PURPLE))
    print(c("  ─────────────────────────", Colors.DIM))

    prod_url = input(f"  Production API URL [{c('http://localhost:3000', Colors.DIM)}]: ").strip()
    if not prod_url:
        prod_url = "http://localhost:3000"

    shadow_url = input(f"  Shadow API URL [{c('http://localhost:4000', Colors.DIM)}]: ").strip()
    if not shadow_url:
        shadow_url = "http://localhost:4000"

    mirror_pct = input(f"  Traffic mirror percentage [{c('100', Colors.DIM)}]: ").strip()
    if not mirror_pct:
        mirror_pct = "100"

    print()
    print(c("  Step 2: Supabase Configuration", Colors.PURPLE))
    print(c("  ──────────────────────────────", Colors.DIM))

    supabase_url = input("  Supabase Project URL: ").strip()
    supabase_anon = input("  Supabase Anon Key: ").strip()
    supabase_db_pass = getpass("  Supabase DB Password: ").strip()

    print()
    print(c("  Step 3: AI Service (Optional)", Colors.PURPLE))
    print(c("  ─────────────────────────────", Colors.DIM))

    gemini_key = getpass("  Gemini API Key (press Enter to skip): ").strip()

    # Extract ports from URLs
    try:
        from urllib.parse import urlparse
        prod_port = urlparse(prod_url).port or 3000
        shadow_port = urlparse(shadow_url).port or 4000
    except Exception:
        prod_port = 3000
        shadow_port = 4000

    # Generate .env
    env_path = os.path.join(root_dir, ".env")
    env_content = f"""# Shadow Deploy Platform Configuration
# Generated by shadowctl init on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

# Supabase
SUPABASE_URL={supabase_url}
SUPABASE_ANON_KEY={supabase_anon}
SUPABASE_DB_PASSWORD={supabase_db_pass}

# AI Service
GEMINI_API_KEY={gemini_key}

# Service Ports
DASHBOARD_PORT=3004
NGINX_PROXY_PORT=8080
API_SERVICE_PORT=8083
AI_SERVICE_PORT=8000
INGESTION_PORT=8081
COMPARISON_PORT=8082
GRAFANA_PORT=3001
PROMETHEUS_PORT=9090
"""
    with open(env_path, "w") as f:
        f.write(env_content)
    print(f"\n  {c('[OK]', Colors.GREEN)} Generated {env_path}")

    # Generate dashboard/.env.local
    dashboard_env_path = os.path.join(root_dir, "dashboard", ".env.local")
    with open(dashboard_env_path, "w") as f:
        f.write(f"VITE_SUPABASE_URL={supabase_url}\n")
        f.write(f"VITE_SUPABASE_ANON_KEY={supabase_anon}\n")
    print(f"  {c('[OK]', Colors.GREEN)} Generated {dashboard_env_path}")

    # Update nginx.conf with upstream ports
    nginx_conf_path = os.path.join(root_dir, "nginx", "nginx.conf")
    if os.path.exists(nginx_conf_path):
        try:
            import re
            with open(nginx_conf_path, "r") as f:
                conf = f.read()
            conf = re.sub(r'(upstream\s+production_backend\s*\{[^}]*server\s+)[^;]+;',
                          f'\\1sample-api-v1:{prod_port};', conf)
            conf = re.sub(r'(upstream\s+shadow_backend\s*\{[^}]*server\s+)[^;]+;',
                          f'\\1sample-api-v2:{shadow_port};', conf)
            with open(nginx_conf_path, "w") as f:
                f.write(conf)
            print(f"  {c('[OK]', Colors.GREEN)} Updated {nginx_conf_path}")
        except Exception as e:
            print(f"  {c('[WARN]', Colors.YELLOW)} Could not update nginx.conf: {e}")

    print(f"\n{c('  Configuration complete!', Colors.GREEN)}")
    print(f"  Run {c('make start', Colors.CYAN)} or {c('docker-compose up -d --build', Colors.CYAN)} to launch.")
    print()


# ── Health Command ──
SERVICES = [
    {"name": "NGINX Proxy", "url": "http://localhost:8080/health", "type": "http", "critical": True},
    {"name": "Ingestion Service", "url": "http://localhost:8081/actuator/health", "type": "http", "critical": True},
    {"name": "Comparison Engine", "url": "http://localhost:8082/actuator/health", "type": "http", "critical": True},
    {"name": "API Service", "url": "http://localhost:8083/actuator/health", "type": "http", "critical": True},
    {"name": "AI Service", "url": "http://localhost:8005/health", "type": "http", "critical": False},
    {"name": "Kafka", "host": "localhost", "port": 29092, "type": "tcp", "critical": True},
    {"name": "Redis", "host": "localhost", "port": 6379, "type": "tcp", "critical": True},
    {"name": "Grafana", "url": "http://localhost:3001", "type": "http", "critical": False},
    {"name": "Prometheus", "url": "http://localhost:9090/-/healthy", "type": "http", "critical": False},
]

def check_http(url, timeout=5):
    try:
        req = urllib.request.urlopen(url, timeout=timeout)
        return {"status": "healthy", "code": req.getcode()}
    except urllib.error.HTTPError as e:
        return {"status": "unhealthy", "code": e.code, "error": str(e)}
    except Exception as e:
        return {"status": "unreachable", "error": str(e)}

def check_tcp(host, port, timeout=3):
    try:
        sock = socket.create_connection((host, port), timeout=timeout)
        sock.close()
        return {"status": "healthy"}
    except Exception as e:
        return {"status": "unreachable", "error": str(e)}

def check_service(svc):
    if svc["type"] == "http":
        return check_http(svc["url"])
    return check_tcp(svc["host"], svc["port"])

def cmd_health(args):
    print(c("\n  Shadow Deploy — Service Health Check", Colors.CYAN))
    print("  " + "=" * 48)

    healthy = 0

    for svc in SERVICES:
        result = check_service(svc)

        if result["status"] == "healthy":
            icon = c("[OK]", Colors.GREEN)
            healthy += 1
        elif svc["critical"]:
            icon = c("[FAIL]", Colors.RED)
        else:
            icon = c("[WARN]", Colors.YELLOW)

        tag = c(" [CRITICAL]", Colors.RED) if svc["critical"] and result["status"] != "healthy" else ""
        print(f"  {icon} {svc['name']:<25} {result['status']}{tag}")

    print("  " + "=" * 48)
    print(f"  {healthy}/{len(SERVICES)} services healthy")

    if healthy == len(SERVICES):
        print(f"\n  {c('All services are operational!', Colors.GREEN)}")
    else:
        print(f"\n  {c('Some services are not responding.', Colors.YELLOW)}")
    print()


# ── Configure Command ──
def cmd_configure(args):
    instruction = args.instruction or input("  Enter configuration instruction: ").strip()
    if not instruction:
        print(c("  No instruction provided.", Colors.RED))
        return

    print(f"\n  {c('Sending to AI configurator...', Colors.CYAN)}")
    try:
        data = json.dumps({"instruction": instruction}).encode()
        req = urllib.request.Request(
            f"{AI_URL}/configure-proxy",
            data=data,
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        resp = urllib.request.urlopen(req, timeout=30)
        result = json.loads(resp.read().decode())
        print(f"  {c('[OK]', Colors.GREEN)} {result.get('message', 'Configuration applied')}")
    except Exception as e:
        print(f"  {c('[FAIL]', Colors.RED)} {e}")
    print()


# ── Test Command ──
def cmd_test(args):
    prod_url = args.prod_url or input("  Production URL: ").strip()
    shadow_url = args.shadow_url or input("  Shadow URL: ").strip()

    if not prod_url or not shadow_url:
        print(c("  Both URLs are required.", Colors.RED))
        return

    paths = ["/", "/api/health"]
    if args.paths:
        paths = [p.strip() for p in args.paths.split(",")]

    print(f"\n  {c('Running comparison tests...', Colors.CYAN)}")
    print(f"  Production: {c(prod_url, Colors.GREEN)}")
    print(f"  Shadow:     {c(shadow_url, Colors.PURPLE)}")
    print()
    print(f"  {'Path':<30} {'Prod':<8} {'Shadow':<8} {'Match':<8} {'Latency':<10}")
    print(f"  {'─' * 64}")

    for path in paths:
        full_prod = prod_url.rstrip("/") + "/" + path.lstrip("/")
        full_shadow = shadow_url.rstrip("/") + "/" + path.lstrip("/")

        # Fetch production
        start = time.time()
        try:
            p_resp = urllib.request.urlopen(full_prod, timeout=5)
            p_status = p_resp.getcode()
            p_body = p_resp.read().decode()
        except urllib.error.HTTPError as e:
            p_status = e.code
            p_body = ""
        except Exception:
            p_status = 0
            p_body = ""
        p_time = (time.time() - start) * 1000

        # Fetch shadow
        start = time.time()
        try:
            s_resp = urllib.request.urlopen(full_shadow, timeout=5)
            s_status = s_resp.getcode()
            s_body = s_resp.read().decode()
        except urllib.error.HTTPError as e:
            s_status = e.code
            s_body = ""
        except Exception:
            s_status = 0
            s_body = ""
        s_time = (time.time() - start) * 1000

        match = p_status == s_status and p_body == s_body
        delta = s_time - p_time
        match_str = c("PASS", Colors.GREEN) if match else c("FAIL", Colors.RED)

        print(f"  {path:<30} {p_status:<8} {s_status:<8} {match_str:<17} {delta:+.0f}ms")

    print()


# ── Status Command ──
def cmd_status(args):
    print(c("\n  Shadow Deploy Platform — Status", Colors.CYAN))
    print("  " + "=" * 48)

    healthy_count = 0
    for svc in SERVICES:
        result = check_service(svc)
        if result["status"] == "healthy":
            icon = c("[OK]", Colors.GREEN)
            healthy_count += 1
        elif svc["critical"]:
            icon = c("[DOWN]", Colors.RED)
        else:
            icon = c("[OFF]", Colors.YELLOW)
        print(f"  {icon} {svc['name']}")

    print(f"\n  Services: {c(str(healthy_count), Colors.GREEN)}/{len(SERVICES)} running")
    print(f"  Dashboard: {c('http://localhost:3004', Colors.CYAN)}")
    print(f"  API:       {c('http://localhost:8083', Colors.CYAN)}")
    print(f"  AI:        {c('http://localhost:8005', Colors.CYAN)}")
    print(f"  Grafana:   {c('http://localhost:3001', Colors.CYAN)}")
    print()


# ── Report Command ──
def cmd_report(args):
    print(c("\n  Shadow API — Validation Report", Colors.CYAN))
    print("  " + "=" * 48)

    print(f"  {c('Environment:', Colors.DIM)}  {c(args.env, Colors.BOLD)}")
    print(f"  {c('Time Range:', Colors.DIM)}   Last {c(args.last, Colors.BOLD)}")
    print(f"  {c('Generated:', Colors.DIM)}    {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print()

    try:
        urllib.request.urlopen("http://localhost:8083/api/v1/health/all", timeout=5)
        print(f"  {c('[OK]', Colors.GREEN)} Connected to API service")
    except Exception:
        print(f"  {c('[WARN]', Colors.YELLOW)} API service not available, showing demo data")

    risk_score = 3.2
    risk_color = Colors.GREEN if risk_score <= 3 else Colors.YELLOW if risk_score <= 6 else Colors.RED
    status = "SAFE" if risk_score <= 5 else "BLOCKED"
    status_color = Colors.GREEN if status == "SAFE" else Colors.RED

    print(f"\n  {c('Overview', Colors.PURPLE)}")
    print(f"  Deployment Risk Score:  {c(f'{risk_score:.1f}', risk_color)} / 10.0")
    print(f"  Status:                 {c(status, status_color)}")
    print(f"\n  Dashboard: {c('http://localhost:3004', Colors.CYAN)}")
    print()


# ── Deployment Status Command ──
def cmd_deployment_status(args):
    print(c("\n  Shadow API — Deployment Status", Colors.CYAN))
    print("  " + "=" * 48)

    build_id = args.build
    risk_score = 3.2
    risk_color = Colors.GREEN if risk_score <= 3 else Colors.YELLOW if risk_score <= 6 else Colors.RED

    print(f"  Build ID:     {c(build_id, Colors.BOLD)}")
    print(f"  Risk Score:   {c(f'{risk_score:.1f}', risk_color)} / 10.0")

    if risk_score <= 5:
        print(f"\n  {c('Recommendation: Safe to promote', Colors.GREEN)}")
    else:
        print(f"\n  {c('Recommendation: Manual review required', Colors.RED)}")
    print()


# ── Main ──
def main():
    parser = argparse.ArgumentParser(
        prog="shadowctl",
        description="Shadow API Validation Platform CLI"
    )
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # init
    subparsers.add_parser("init", help="Interactive setup wizard")

    # health
    subparsers.add_parser("health", help="Check all service health")

    # configure
    cfg_parser = subparsers.add_parser("configure", help="Natural language NGINX configuration")
    cfg_parser.add_argument("instruction", nargs="?", default=None, help="Configuration instruction")

    # test
    test_parser = subparsers.add_parser("test", help="Quick website comparison test")
    test_parser.add_argument("--prod-url", dest="prod_url", default=None, help="Production URL")
    test_parser.add_argument("--shadow-url", dest="shadow_url", default=None, help="Shadow URL")
    test_parser.add_argument("--paths", default=None, help="Comma-separated paths to test")

    # status
    subparsers.add_parser("status", help="Show platform status")

    # report
    report_parser = subparsers.add_parser("report", help="Generate validation report")
    report_parser.add_argument("--env", default="staging", help="Environment")
    report_parser.add_argument("--last", default="1h", help="Time range")

    # deployment-status
    deploy_parser = subparsers.add_parser("deployment-status", help="Check deployment status")
    deploy_parser.add_argument("--build", required=True, help="Build ID")

    args = parser.parse_args()

    commands = {
        "init": cmd_init,
        "health": cmd_health,
        "configure": cmd_configure,
        "test": cmd_test,
        "status": cmd_status,
        "report": cmd_report,
        "deployment-status": cmd_deployment_status,
    }

    if args.command in commands:
        commands[args.command](args)
    else:
        parser.print_help()
        print(f"\n  Available commands: {', '.join(commands.keys())}")
        sys.exit(1)


if __name__ == "__main__":
    main()
